### PR TITLE
fix(src) fix search cookie domain attribute

### LINKED ISSUE #49: Does not work search domain logic

### PR DESCRIPTION
**Pull request by 9renpoto**
Closes #49 

- Bugfix: select cookie domain
- Added: domain check tests

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -15,14 +15,13 @@ function setCookie (
   let attr: cookies.CookieAttributes = options
   for (let i = 2; i <= domainParts.length; i++) {
     domain = `${domainParts[domainParts.length - i]}.${domain}`
-    attr = Object.assign({}, options, { domain })
-    cookies.set(name, data, options)
-    const storedId = cookies.get(name)
-    if (storedId) {
-      return storedId
+    attr.domain = domain
+    cookies.set(name, data, attr)
```
Comment (9renpoto) [inline src/index.ts]: needs rewrite domain attribute

File: src/index.ts [hunk 2]
```diff
@@ -42,9 +41,8 @@ function findOrCreate (
     return cookies.get(name)
   }
 
-  let created
```
Comment (9renpoto) [inline src/index.ts]: unused
